/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package b;

import a.Llamada;

/**
 *
 * @author HPUSER
 */
public class JFrameLlamada extends javax.swing.JFrame {

    
    public JFrameLlamada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxTPlan = new javax.swing.JComboBox<>();
        cbxTLlamada = new javax.swing.JComboBox<>();
        btnCalcular = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        txtDni = new javax.swing.JTextField();
        txtMinuLlamada = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxTPlan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TIPO DE PLAN", "A", "B" }));
        getContentPane().add(cbxTPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 110, -1));

        cbxTLlamada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TIPO DE LLAMADA", "LOCAL", "CELULAR" }));
        getContentPane().add(cbxTLlamada, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 120, 30));

        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, -1, -1));

        jButton3.setText("SALIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, -1, -1));

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 530, 300));
        getContentPane().add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 90, 30));
        getContentPane().add(txtMinuLlamada, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 80, 30));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 100, 30));

        jLabel1.setText("Minuto por llamada");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel2.setText("DNI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        String dni=txtDni.getText();
        String nom=txtNombre.getText();
        String tPlan=cbxTPlan.getSelectedItem().toString();
        String tLamada=cbxTLlamada.getSelectedItem().toString();
        int minuLlamada=Integer.parseInt(txtMinuLlamada.getText());
        Llamada l=new Llamada(dni, nom, tPlan, tLamada, minuLlamada);
        txtArea.append("El dni: "+l.getDni());
        txtArea.append("\nEl nombre: "+l.getNombre());
        txtArea.append("\nEl tipo de Llamada: "+l.getTipoLlamada());
        txtArea.append("\nEl tipo de Plan: "+l.getTipoPlan());
        txtArea.append("\n---------------------------");
        txtArea.append("\nCalcular costo por minuto: "+String.valueOf(l.calcularCostoPorMinuto()));
        txtArea.append("\nCosto de llamada: "+String.valueOf(l.costoDeLlamada()));
        txtArea.append("\nPago final por llamada: "+String.valueOf(l.pagoFinalPorLLamada()));
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameLlamada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameLlamada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameLlamada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameLlamada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameLlamada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> cbxTLlamada;
    private javax.swing.JComboBox<String> cbxTPlan;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtMinuLlamada;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
